### PR TITLE
Passing a Gulp PluginError to gulp's callback.

### PR DESCRIPTION
**Pull request by joeycozza**
By doing this, when there are vulnerabilities found with nsp, gulp will error out and output those vulnerabilities without logging the error stack. 

This takes care of the issue found here [https://github.com/nodesecurity/gulp-nsp/issues/12](https://github.com/nodesecurity/gulp-nsp/issues/12) where it explains much more in depth what is going on, and how to recreate the issue.

### CODE REVIEW

**Comment by nlf** [comment]
sorry for letting this sit so long, this is great though.

one nit, however, is that we prefer to keep the shrinkwrap file as minimal as possible. i wrote a tool to help with this called [shrinkydink](https://github.com/nlf/shrinkydink). if you install it globally and run it from the directory that contains npm-shrinkwrap.json it will clean up the file for us. once that's done, i'm happy to merge this

**Comment by joeycozza** [comment]
Hey, I'd be happy to run shrinkydink. Does it matter that I used npm@2 to install node_modules? The shrinkwrap file looks WAY different from the one that was already created. Is that a problem?

**Comment by nlf** [comment]
For right now, I think running it with npm2 may be best anyway. We've had some issues with npm3 and shrinkwrap files

**Comment by joeycozza** [comment]
Okay, then the PR should be all good to go.

**Pull request merged**
